create: true

alloy:
  namespaceOverride: alloy

  controller:
    type: deployment    # เปลี่ยนจาก daemonset → ไม่ชนกับ alloy เดิม
    replicas: 1

  alloy:
    configMap:
      create: false
      name: ccp-1-cm-alloy-poc

    extraPorts:
      - name: loki-push
        port: 3100
        targetPort: 3100
        protocol: TCP
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

  image:
    registry: docker.io
    repository: grafana/alloy
    tag: "v1.17.0"

  configReloader:
    enabled: false
